Repository BullpenRE/bullpen, pull requests merged in 2021-04, with the labels that each got.

#352 BP-409 Display paid invoices with a link to it for employers
  app/models/timesheet.rb
  app/services/stripe/customers/invoice_service.rb
  app/views/employer/contracts/index.html.erb
  app/views/shared/contracts/_invoice_history.html.erb
  lib/tasks/stripe.rake
Labels: qa done, review done

#358 BP-412 Add field and links in the Employer Profile in Active Admin
  app/admin/employer_profiles_aa.rb
Labels: review done

#346 BP-389/401 Make an email review of pending payment for the employer
  app/mailers/employer_mailer.rb
  app/models/timesheet.rb
  app/services/employer_review_pending_payment_service.rb
  app/views/employer_mailer/review_pending_payment.html.erb
  lib/tasks/messages.rake
  spec/models/timesheet_spec.rb
  test/mailers/previews/employer_mailer_preview.rb
Labels: in testing, int2, review done

#298 BP-357: Create initial mixpanel tracking
  Gemfile
  Gemfile.lock
  README.md
  app/controllers/concerns/create_contract.rb
  app/controllers/confirmations_controller.rb
  app/controllers/employer/contracts_controller.rb
  app/controllers/employer/interviews_controller.rb
  app/controllers/employer/job_flows_controller.rb
  app/controllers/employer/jobs_controller.rb
  app/controllers/employer/reviews_controller.rb
  app/controllers/employer/talent_controller.rb
  app/controllers/employer_profile_steps_controller.rb
  app/controllers/freelancer/application_flows_controller.rb
  app/controllers/freelancer/applications_controller.rb
  app/controllers/freelancer/contracts_controller.rb
  app/controllers/freelancer/interviews_controller.rb
  app/controllers/freelancer/jobs_controller.rb
  app/controllers/freelancer_profile_steps_controller.rb
  app/views/devise/sessions/new.html.erb
  app/views/join/index.html.erb
  app/views/layouts/application.html.erb
  app/workers/mixpanel_worker.rb
  config/application.rb
  config/environments/development.rb
  lib/mixpanel_tracker.rb
Labels: qa done, review done
